services:
  opencode:
    image: zayneliu/opencode:0.0.2
    container_name: opencode
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    network_mode: host
    volumes:
      - ./workspace:/root/workspace/
      - opencode-config:/root/.config/opencode
      - opencode-data:/root/.local/share/opencode
      - opencode-cache:/root/.cache/opencode
    command: sleep infinity # or: tail -f /dev/null

volumes:
  opencode-config:
  opencode-data:
  opencode-cache:
